export const ICONS = {
    back: require('../assets/food/icons/back.png'),
    car: require('../assets/food/icons/car.png'),
    cutlery: require('../assets/food/icons/cutlery.png'),
    drink: require('../assets/food/icons/drink.png'),
    fire: require('../assets/food/icons/fire.png'),
    fries: require('../assets/food/icons/fries.png'),
    hamburger: require('../assets/food/icons/hamburger.png'),
    hotdog: require('../assets/food/icons/hotdog.png'),
    like: require('../assets/food/icons/like.png'),
    list: require('../assets/food/icons/list.png'),
    location: require('../assets/food/icons/location.png'),
    mastercard: require('../assets/food/icons/mastercard.png'),
    nearby: require('../assets/food/icons/nearby.png'),
    noodle: require('../assets/food/icons/noodle.png'),
    pin: require('../assets/food/icons/pin.png'),
    pizza: require('../assets/food/icons/pizza.png'),
    red_pin: require('../assets/food/icons/red-pin.png'),
    rice_bowl: require('../assets/food/icons/rice-bowl.png'),
    salad: require('../assets/food/icons/salad.png'),
    search: require('../assets/food/icons/search.png'),
    shopping_basket: require('../assets/food/icons/shopping-basket.png'),
    star: require('../assets/food/icons/star.png'),
    sushi: require('../assets/food/icons/sushi.png'),
    user: require('../assets/food/icons/user.png')
}

export const IMAGES = {
    avatar_1: require('../assets/food/images/avatar-1.jpg'),
    avatar_2: require('../assets/food/images/avatar-2.jpg'),
    avatar_3: require('../assets/food/images/avatar-3.jpg'),
    avatar_4: require('../assets/food/images/avatar-4.jpg'),
    avatar_5: require('../assets/food/images/avatar-5.jpg'),
    baked_fries: require('../assets/food/images/baked-fries.jpg'),
    burger_restaurant_2: require('../assets/food/images/burger-restaurant-2.jpg'),
    burger_restaurant: require('../assets/food/images/burger-restaurant.jpg'),
    chicago_hot_dog: require('../assets/food/images/chicago-hot-dog.jpg'),
    crispy_chicken_burger: require('../assets/food/images/crispy-chicken-burger.jpg'),
    fries_restaurant: require('../assets/food/images/fries-restaurant.jpg'),
    hawaiian_pizza: require('../assets/food/images/hawaiian-pizza.jpg'),
    honey_mustard_chicken_burger: require('../assets/food/images/honey-mustard-chicken-burger.jpg'),
    hot_dog_restaurant: require('../assets/food/images/hot-dog-restaurant.jpg'),
    ice_kacang: require('../assets/food/images/ice-kacang.jpg'),
    japanese_restaurant: require('../assets/food/images/japanese-restaurant.jpg'),
    kek_lapis_shop: require('../assets/food/images/kek-lapis-shop.jpg'),
    kek_lapis: require('../assets/food/images/kek-lapis.jpg'),
    kolo_mee: require('../assets/food/images/kolo-mee.jpg'),
    nasi_briyani_mutton: require('../assets/food/images/nasi-briyani-mutton.jpg'),
    nasi_lemak: require('../assets/food/images/nasi-lemak.jpg'),
    noodle_shop: require('../assets/food/images/noodle-shop.jpg'),
    pizza_restaurant: require('../assets/food/images/pizza-restaurant.jpg'),
    pizza: require('../assets/food/images/pizza.jpg'),
    salad: require('../assets/food/images/salad.jpg'),
    sarawak_laksa: require('../assets/food/images/sarawak-laksa.jpg'),
    sushi: require('../assets/food/images/sushi.jpg'),
    teh_c_peng: require('../assets/food/images/teh-c-peng.jpg'),
    tomato_pasta: require('../assets/food/images/tomato-pasta.jpg'),
}